from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')

@register_library
class LibraryDcm(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS', CWD, "$NvM_Cfg", "$PduR_Cfg"]
        self.source = objs

    
