from building import *


objs = Glob('*.c')

@register_library
class LibraryStdTimer(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS']
        self.source = objs
        if IsBuildForWindows(self.GetCompiler()):
            self.LIBS += ['winmm']


    
