from building import *

CWD = GetCurrentDir()
objs = Glob("*.c")


@register_library
class LibrarySRec(Library):
    def config(self):
        self.include = CWD
        self.LIBS = ["Crc"]
        self.CPPPATH = ["$INFRAS"]
        self.source = objs

objsSrecCat = Glob("utils/srec_cat.cpp")

@register_application
class ApplicationSRecCat(Application):
    def config(self):
        self.include = CWD
        self.LIBS = ["SRec", "Utils"]
        self.CPPPATH = ["$INFRAS"]
        self.source = objsSrecCat