from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')

@register_library
class LibraryCanTSyn(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS', CWD]
        self.LIBS = ['Crc']
        self.source = objs

    
