from building import *

CWD = GetCurrentDir()

objs = Glob('src/*.cpp')

RegisterCPPPATH('$Utils', '%s/include'%(CWD))

@register_library
class LibraryUtils(Library):
    def config(self):
        self.include = ['%s/include'%(CWD)]
        self.source = objs
