from building import *

CWD = GetCurrentDir()

objs = Glob('src/*.cpp')

@register_library
class LibraryUtils(Library):
    def config(self):
        self.include = ['%s/include'%(CWD)]
        self.CPPPATH = ['$INFRAS']
        self.source = objs
