from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')

@register_library
class LibraryNvM(Library):
    def config(self):
        self.include = CWD
        self.LIBS = ['Crc']
        self.CPPPATH = ['$INFRAS']
        self.source = objs

    
