from building import *

CWD = GetCurrentDir()
objs = Glob("*.c")


@register_library
class LibraryCsm(Library):
    def config(self):
        self.CPPPATH = ["$INFRAS", CWD]
        self.source = objs
        be = os.getenv("CSM_BACKEND", "mbedtls")
        if be == "mbedtls":
            self.LIBS += ["MbedTls"]
        else:
            raise
