from building import *
for sc in Glob('*/SConscript'):
    SConscript(sc)

CWD = GetCurrentDir()
objs = Glob('*.cpp')


@register_library
class LibraryAsPy(Library):
    shared = True
    compiler = 'PYCC'

    def config(self):
        self.LIBS = ['CanLib', 'IsoTp']
        self.Append(CPPDEFINES=['USE_STD_DEBUG', 'USE_STD_PRINTF'])
        self.CPPPATH = ['$INFRAS']
        self.source = objs
