from building import *

CWD = GetCurrentDir()

objs = Glob('*.c')


@register_library
class LibraryPCap(Library):
    def config(self):
        self.include = CWD
        self.CPPPATH = ['$INFRAS']
        self.source = objs
