from building import *

CWD = GetCurrentDir()

objs = Glob('*.c')

@register_library
class LibraryFactory(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS']
        self.source = objs

    
