from building import *

CWD = GetCurrentDir()
objs = Glob("*.c")


@register_library
class LibraryNm(Library):
    def config(self):
        self.CPPPATH = ["$INFRAS", CWD]
        self.source = objs
