from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')

@register_library
class LibraryCom(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS', '$PduR_Cfg', CWD]
        self.LIBS = ['StdBit']
        self.source = objs

    
