from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')
@register_library
class LibraryOsekNm(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS', '$CanIf_Cfg', CWD]
        self.source = objs

    
