# SSAS - Simple Smart Automotive Software
# Copyright (C) 2024 Parai Wang <parai@foxmail.com>

__all__ = ["ldf"]

from . import ascyacc


def post_process_messages(p):
    p["messages"] = []
    frames = p.get("frames", {})
    signals = p.get("signals", {})
    for name, frame in frames.items():
        msg = {"name": name, "id": frame["id"], "node": frame["publisher"], "dlc": frame["dlc"], "signals": []}
        for sname, sigi1 in frame["signals"].items():
            sigi2 = signals[sname]
            size = eval(sigi2["size"])
            signal = {
                "name": sname,
                "start": sigi1["start"],
                "size": sigi2["size"],
                "endian": "little",
                "sign": "+",
                "factor": 1,
                "offset": 0,
                "min": 0,
                "max": (1 << size - 1),
                "unit": "",
                "InitValue": sigi2["initial"],
                "node": sigi2["subscriber"],
            }
            msg["signals"].append(signal)
        msg["signals"].sort(key=lambda x: eval(x["start"]))
        p["messages"].append(msg)
    p["messages"].sort(key=lambda x: eval(x["id"]))


def parse(file):
    print(f"LDF: {file}")
    fp = open(file, "r")
    data = fp.read()
    fp.close()
    p = ascyacc.parse(data)
    post_process_messages(p)
    return p


def save_dbc(p, dbc):
    f = open(dbc, "w")
    nodes = []
    for msg in p["messages"]:
        if msg["node"] not in nodes:
            nodes.append(msg["node"])
    f.write(
        """VERSION "generated by AS ldf tool"


NS_ :
    NS_DESC_
    CM_
    BA_DEF_
    BA_
    VAL_
    CAT_DEF_
    CAT_
    FILTER
    BA_DEF_DEF_
    EV_DATA_
    ENVVAR_DATA_
    SGTYPE_
    SGTYPE_VAL_
    BA_DEF_SGTYPE_
    BA_SGTYPE_
    SIG_TYPE_REF_
    VAL_TABLE_
    SIG_GROUP_
    SIG_VALTYPE_
    SIGTYPE_VALTYPE_
    BO_TX_BU_
    BA_DEF_REL_
    BA_REL_
    BA_DEF_DEF_REL_
    BU_SG_REL_
    BU_EV_REL_
    BU_BO_REL_
    SG_MUL_VAL_

BS_:

BU_: %s\n\n"""
        % (" ".join(nodes))
    )
    for msg in p["messages"]:
        idx = eval(msg["id"])
        f.write("\nBO_ %s %s: %s %s\n" % (idx, msg["name"], msg["dlc"], msg["node"]))
        for sig in msg["signals"]:
            f.write(
                ' SG_ %s : %s|%s@%s%s (%s,%s) [%s|%s] "" %s\n'
                % (
                    sig["name"],
                    sig["start"],
                    sig["size"],
                    0 if sig["endian"] == "big" else 1,
                    sig["sign"],
                    sig["factor"],
                    sig["offset"],
                    sig["min"],
                    sig["max"],
                    ",".join(sig["node"]),
                )
            )
    msgPeriod = {}
    schtbls = p["schedule_tables"]
    for sname, schtbl in schtbls.items():
        period = 0
        for entry in schtbl:
            period = period + eval(entry["delay"])
        for entry in schtbl:
            msgPeriod[entry["name"]] = period

    f.write('\n\nCM_ " ";\n')
    f.write('BA_DEF_ BO_  "GenMsgCycleTime" INT 0 0;\n')
    f.write('BA_DEF_DEF_  "GenMsgCycleTime" 0;\n')
    for msg in p["messages"]:
        if msg["name"] in msgPeriod:
            idx = eval(msg["id"])
            f.write('BA_ "GenMsgCycleTime" BO_ %s %s;\n' % (idx, msgPeriod[msg["name"]]))
    f.write("\n\n\n\n\n\n")
    f.close()


def ldf(path, dbc=None):
    p = parse(path)
    if dbc != None:
        save_dbc(p, dbc)
    return p
