from building import *

CWD = GetCurrentDir()

objs = Glob('*.c')


@register_library
class LibraryShell(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS']
        self.LIBS = ['RingBuffer']
        self.source = objs
