from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')

@register_library
class LibraryDem(Library):
    def config(self):
        self.include = CWD
        self.CPPPATH = ['$INFRAS', "$NvM_Cfg"]
        self.source = objs

    
