from building import *

CWD = GetCurrentDir()
objs = Glob("*.cpp")


@register_library
class LibraryODX(Library):
    def config(self):
        pkg = Package("https://github.com/leethomason/tinyxml2.git", version="9.0.0")
        self.include = [CWD]
        self.CPPPATH = [pkg]
        self.source = objs + PkgGlob(pkg, ["tinyxml2.cpp"])


objsCat = Glob("utils/odx_cat.c")


@register_application
class ApplicationOdxCat(Application):
    def config(self):
        self.LIBS = ["ODX"]
        self.source = objsCat
