from building import *

CWD = GetCurrentDir()
objs = Glob("*.c")


@register_driver
class DriverLin(Driver):
    cls = "as"

    def config(self):
        self.include = [CWD]
        self.CPPPATH = ["$INFRAS"]
        self.source = objs
