from building import *

CWD = GetCurrentDir()
objs = Glob("*.c")
objscpp = Glob("cpp/src/*.cpp")


@register_library
class LibrarySomeIp(Library):
    object = True

    def config(self):
        self.CPPDEFINES = []
        self.CPPPATH = ["$INFRAS", CWD]
        self.LIBS = ["SoAd", "MemPool", "OSAL"]
        self.source = objs
        if IsBuildForHost(self.GetCompiler()):
            USE_PCAP = os.getenv("USE_PCAP")
            if USE_PCAP == "YES":
                self.LIBS += ["PCap"]
                self.CPPDEFINES += ["USE_PCAP"]
            self.include += ["%s/cpp/include" % (CWD)]
            self.LIBS += ["Utils", "Plugin"]
            self.source += objscpp
            if not IsBuildForWindows():
                self.CXXFLAGS = ["--std=c++17"]
