from building import *

objs = Glob('src/*.c')


@register_library
class LibrarySimulator(Library):
    def config(self):
        self.LIBS = ['CanLib']
        self.CPPPATH = ['$INFRAS']
        self.source = objs

objsFlsAc = Glob('src/FlsAc.c') + Glob('src/critical.c')
@register_library
class LibraryFlsAc(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS']
        self.source = objsFlsAc
