from building import *

CWD = GetCurrentDir()

objs = Glob('*.c')

@register_library
class LibraryLibC(Library):
    def config(self):
        self.source = objs
        self.CPPPATH = ['$INFRAS']
        self.LIBS = ['RingBuffer']

    
