from building import *

CWD = GetCurrentDir()
objs = Glob("*.c")


@register_library
class LibraryDio(Library):
    def config(self):
        self.include = [CWD]
        self.CPPPATH = ["$INFRAS", "$Port_Cfg"]
        self.LIBS += ["Port"]
        self.source = objs
