/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "X509"
 * 	found in "x509.asn1"
 * 	`asn1c -fwide-types`
 */

#include "DateTime.h"

static asn_TYPE_member_t asn_MBR_DateTime_1[] = {
  {ATF_NOFLAGS, 0, offsetof(struct DateTime, choice.utcTime), (ASN_TAG_CLASS_UNIVERSAL | (23 << 2)),
   0, &asn_DEF_UTCTime, 0, /* Defer constraints checking to the member type */
   0,                      /* PER is not compiled, use -gen-PER */
   0, "utcTime"},
  {ATF_NOFLAGS, 0, offsetof(struct DateTime, choice.generalTime),
   (ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 0, &asn_DEF_GeneralizedTime,
   0, /* Defer constraints checking to the member type */
   0, /* PER is not compiled, use -gen-PER */
   0, "generalTime"},
};
static const asn_TYPE_tag2member_t asn_MAP_DateTime_tag2el_1[] = {
  {(ASN_TAG_CLASS_UNIVERSAL | (23 << 2)), 0, 0, 0}, /* utcTime */
  {(ASN_TAG_CLASS_UNIVERSAL | (24 << 2)), 1, 0, 0}  /* generalTime */
};
static asn_CHOICE_specifics_t asn_SPC_DateTime_specs_1 = {
  sizeof(struct DateTime),
  offsetof(struct DateTime, _asn_ctx),
  offsetof(struct DateTime, present),
  sizeof(((struct DateTime *)0)->present),
  asn_MAP_DateTime_tag2el_1,
  2, /* Count of tags in the map */
  0,
  -1 /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DateTime = {
  "DateTime",
  "DateTime",
  CHOICE_free,
  CHOICE_print,
  CHOICE_constraint,
  CHOICE_decode_ber,
  CHOICE_encode_der,
  CHOICE_decode_xer,
  CHOICE_encode_xer,
  0,
  0, /* No PER support, use "-gen-PER" to enable */
  CHOICE_outmost_tag,
  0, /* No effective tags (pointer) */
  0, /* No effective tags (count) */
  0, /* No tags (pointer) */
  0, /* No tags (count) */
  0, /* No PER visible constraints */
  asn_MBR_DateTime_1,
  2,                        /* Elements count */
  &asn_SPC_DateTime_specs_1 /* Additional specs */
};
