/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "X509"
 * 	found in "x509.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef _DateTime_H_
#define _DateTime_H_

#include <asn_application.h>

/* Including external dependencies */
#include <UTCTime.h>
#include <GeneralizedTime.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DateTime_PR {
  DateTime_PR_NOTHING, /* No components present */
  DateTime_PR_utcTime,
  DateTime_PR_generalTime
} DateTime_PR;

/* DateTime */
typedef struct DateTime {
  DateTime_PR present;
  union DateTime_u {
    UTCTime_t utcTime;
    GeneralizedTime_t generalTime;
  } choice;

  /* Context for parsing across buffer boundaries */
  asn_struct_ctx_t _asn_ctx;
} DateTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DateTime;

#ifdef __cplusplus
}
#endif

#endif /* _DateTime_H_ */
#include <asn_internal.h>
