from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')

@register_library
class LibraryDoIP(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS', CWD]
        self.LIBS = ['SoAd', 'MemPool']
        self.source = objs

