from building import *

CWD = GetCurrentDir()
objs = Glob('*.c')

use_lwip = os.getenv('USE_LWIP')


@register_library
class LibraryTcpIp(Library):
    def config(self):
        self.CPPPATH = ['$INFRAS', CWD]
        if 'YES' == use_lwip:
            self.LIBS = ['LWIP']
            self.CPPDEFINES = ['USE_LWIP']
        else:
            if IsBuildForWindows():
                self.LIBS = ['ws2_32']
        self.source = objs
