@startuml Fee_Init

start
:BankId = 0;
while (BankId < NumOfBanks) is (yes)
    :ReadBankAdmin;
    if (Magic Number Correct) then (yes)
        :BlankCheckInfo;
        :BlankCheckBlock;
    else (no)
        :EraseInvalidBank;
    endif
    :BankId++;
endwhile(no)
:CheckBankInfo;
:CheckBankMagic;
:GetWorkingBank;
:SearchFreeSpace;
if (WorkingBank Full) then (yes)
    :Backup; <<procedure>>
    kill
else (no)
    stop
endif
@enduml
